// plugins/builtin-ui/src/main/frontend/UiCard.tsx
import { useRef } from 'preact/hooks'
import { useCfg, useContainerQuery, findAction, runAction, resolveParams, sessionStore, Container, type BindingContext, type CardConfig } from '@cutcrft/runtime-client'
import type { ComponentProps } from './common'

export default function UiCard(props: ComponentProps) {
  const root = useRef<HTMLDivElement | null>(null)
  const cq = useContainerQuery(root)
  const cfg = useCfg<CardConfig>(props.config, { bordered: true, padding: 'var(--rt-space-lg)' })

  async function headerActionClick(command: string | undefined, params: Record<string, unknown> | undefined): Promise<void> {
    if (command) {
      runAction(findAction(cfg.value.actions, 'headerAction'), {
        ...(props.context ?? {}),
        payload: { command, params: resolveParams(params, props.context ?? {}) }
      })
      await sessionStore.executeCommand(command, resolveParams(params, props.context ?? {}))
    }
  }

  const context = props.context
  return (
    <section
      ref={root}
      class={`ui-card ui-card--cq-${cq.value}${cfg.value.bordered ? ' ui-card--bordered' : ''}${cfg.value.className ? ' ' + cfg.value.className : ''}`}
      style={cfg.value.style}
    >
      {cfg.value.title || cfg.value.subtitle || cfg.value.headerActions?.length ? (
        <header class="ui-card__header">
          <div class="ui-card__heading">
            {cfg.value.title ? <h3 class="ui-card__title">{cfg.value.title}</h3> : null}
            {cfg.value.subtitle ? <p class="ui-card__subtitle">{cfg.value.subtitle}</p> : null}
          </div>
          {cfg.value.headerActions ? (
            <div class="ui-card__actions">
              {cfg.value.headerActions.map((action, index) => (
                <button
                  key={index}
                  class={`ui-button ui-button--${action.variant ?? 'default'} ui-button--small`}
                  onClick={() => headerActionClick(action.command ?? '', action.params)}
                >
                  {action.label}
                </button>
              ))}
            </div>
          ) : null}
        </header>
      ) : null}
      <div class="ui-card__body" style={{ padding: cfg.value.padding }}>
        {(cfg.value.components ?? []).map((child, index) => (
          <Container key={index} component={child} context={context} />
        ))}
      </div>
    </section>
  )
}

// frontend/src/components/UiCard.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useCfg } from '../renderer/useConfig'
import { useContainerQuery } from '../renderer/useContainerQuery'
import { runAction, findAction, resolveParams } from '../renderer/bindingEngine'
import { sessionStore } from '../store/session'
import ComponentHost from './ComponentHost.vue'
import type { BindingContext, CardConfig } from '../protocol/componentSpec'

const props = defineProps<{ config: Record<string, unknown>; context?: BindingContext }>()

const root = ref<HTMLElement | null>(null)
const cq = useContainerQuery(root)

const cfg = useCfg<CardConfig>(props.config, {
  bordered: true,
  padding: 'var(--rt-space-lg)'
})

async function headerActionClick(
  command: string | undefined,
  params: Record<string, unknown> | undefined
): Promise<void> {
  if (command) {
    runAction(findAction(cfg.value.actions, 'headerAction'), {
      ...(props.context ?? {}),
      payload: { command, params: resolveParams(params, props.context ?? {}) }
    })
    await sessionStore.executeCommand(command, resolveParams(params, props.context ?? {}))
  }
}
</script>

<template>
  <section
    ref="root"
    class="ui-card"
    :class="[cfg.className, `ui-card--cq-${cq}`, { 'ui-card--bordered': cfg.bordered }]"
    :style="cfg.style"
  >
    <header v-if="cfg.title || cfg.subtitle || cfg.headerActions?.length" class="ui-card__header">
      <div class="ui-card__heading">
        <h3 v-if="cfg.title" class="ui-card__title">{{ cfg.title }}</h3>
        <p v-if="cfg.subtitle" class="ui-card__subtitle">{{ cfg.subtitle }}</p>
      </div>
      <div v-if="cfg.headerActions" class="ui-card__actions">
        <button
          v-for="(action, index) in cfg.headerActions"
          :key="index"
          class="ui-button"
          :class="[`ui-button--${action.variant ?? 'default'}`, 'ui-button--small']"
          @click="headerActionClick(action.command ?? '', action.params)"
        >
          {{ action.label }}
        </button>
      </div>
    </header>
    <div class="ui-card__body" :style="{ padding: cfg.padding }">
      <ComponentHost
        v-for="(child, index) in cfg.components ?? []"
        :key="index"
        :component="child"
        :context="context"
      />
    </div>
  </section>
</template>

<style scoped>
.ui-card {
  background: var(--rt-color-surface);
  border-radius: var(--rt-radius);
  overflow: hidden;
}
.ui-card--bordered {
  border: 1px solid var(--rt-color-border);
}
.ui-card__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--rt-space-sm);
  padding: var(--rt-space) var(--rt-space-lg);
  border-bottom: 1px solid var(--rt-color-border);
}
.ui-card__title {
  margin: 0;
  font-size: var(--rt-font-size-lg);
}
.ui-card__subtitle {
  margin: 0.1rem 0 0;
  font-size: var(--rt-font-size-sm);
  color: var(--rt-color-muted);
}
.ui-card__actions {
  display: flex;
  gap: var(--rt-space-xs);
}
.ui-card__body {
  display: flex;
  flex-direction: column;
  gap: var(--rt-space);
}
.ui-card--cq-sm .ui-card__header {
  flex-direction: column;
  align-items: flex-start;
  padding: var(--rt-space-sm) var(--rt-space);
}
.ui-card--cq-sm .ui-card__title {
  font-size: var(--rt-font-size);
}
</style>
