// modules/ui-base/frontend/src/primitives/Stack.tsx
import type { ComponentChildren } from 'preact'
import * as styles from './styles.css'

interface StackProps {
  direction?: 'vertical' | 'horizontal'
  gap?: string
  align?: string
  justify?: string
  wrap?: boolean
  padding?: string
  children?: ComponentChildren
}

export function Stack(props: StackProps) {
  const dir = props.direction ?? 'vertical'
  return (
    <div
      class={`${dir === 'vertical' ? styles.stackVertical : styles.stackHorizontal} ${props.wrap ? styles.stackWrap : ''} ${styles.stack}`}
      style={{
        gap: props.gap,
        alignItems: props.align,
        justifyContent: props.justify,
        padding: props.padding,
      }}
    >
      {props.children}
    </div>
  )
}

// frontend/src/core/primitives/Stack.vue
<script setup lang="ts">
defineProps<{
  direction?: 'vertical' | 'horizontal'
  gap?: string
  align?: string
  justify?: string
  wrap?: boolean
  padding?: string
}>()
</script>

<template>
  <div
    class="stack"
    :class="[`stack--${direction ?? 'vertical'}`, { 'stack--wrap': wrap }]"
    :style="{
      gap: gap,
      alignItems: align,
      justifyContent: justify,
      padding: padding
    }"
  >
    <slot />
  </div>
</template>

<style scoped>
.stack {
  display: flex;
  min-width: 0;
  min-height: 0;
}
.stack--vertical {
  flex-direction: column;
}
.stack--horizontal {
  flex-direction: row;
}
.stack--wrap {
  flex-wrap: wrap;
}
</style>
