// modules/ui-base/frontend/src/overlay/OverlayHost.tsx
import { overlayService } from '@cutcrft/plugin-sdk'
import { ContextMenuHost } from './ContextMenuHost'
import { ModalHost } from './ModalHost'
import { PanelHost } from './PanelHost'
import { TooltipHost } from './TooltipHost'
import { createPortal } from 'preact/compat'

export function OverlayHost() {
  const { overlaysSignal } = overlayService
  const overlays = overlaysSignal.value

  const rendered = overlays.map((instance) => {
    switch (instance.definition.kind) {
      case 'menu':
        return <ContextMenuHost key={instance.uid} instance={instance} />
      case 'modal':
        return <ModalHost key={instance.uid} instance={instance} />
      case 'panel':
        return <PanelHost key={instance.uid} instance={instance} />
      case 'tooltip':
        return <TooltipHost key={instance.uid} instance={instance} />
      default:
        return null
    }
  })

  return createPortal(<>{rendered}</>, document.body)
}

// frontend/src/overlay/OverlayHost.vue
<script setup lang="ts">
import { computed } from 'vue'
import { overlayService } from './overlayService'
import ContextMenuHost from './ContextMenuHost.vue'
import ModalHost from './ModalHost.vue'
import PanelHost from './PanelHost.vue'
import TooltipHost from './TooltipHost.vue'

const overlays = computed(() => overlayService.overlays)
</script>

<template>
  <teleport to="body">
    <template v-for="instance in overlays" :key="instance.uid">
      <ContextMenuHost v-if="instance.definition.kind === 'menu'" :instance="instance" />
      <ModalHost v-else-if="instance.definition.kind === 'modal'" :instance="instance" />
      <PanelHost v-else-if="instance.definition.kind === 'panel'" :instance="instance" />
      <TooltipHost v-else-if="instance.definition.kind === 'tooltip'" :instance="instance" />
    </template>
  </teleport>
</template>
